/* eslint-disable */
// This file is generated by scripts/inspect-shipping-v2-schema.mjs.
// Do not edit by hand. Run: npm run shipping-v2:schema

export const SHIPPING_V2_SCHEMA_GENERATED_AT = "2026-06-10T21:50:43.393Z";

export const SHIPPING_V2_TABLES = {
  "proveedores": "Shipping Proveedores",
  "items": "Shipping Items",
  "pagos": "Shipping Pagos",
  "finanzasMovimientos": "Shipping Finanzas Movimientos",
  "packings": "Shipping Packings",
  "recepciones": "Shipping Recepciones",
  "novedades": "Shipping Novedades",
  "migraciones": "Shipping Migraciones",
  "eventos": "Shipping Eventos",
  "cpuCatalog": "Catálogo CPUs",
  "computerCatalog": "Catálogo Computadores",
  "connectivityCatalog": "Catálogo Conectividad",
  "portsCatalog": "Catálogo Puertos",
  "extraFeaturesCatalog": "Catálogo Características Extras"
} as const;

export const SHIPPING_V2_ITEM_FIELDS = {
  "sku": "SKU",
  "nombre": "Nombre del item",
  "aiNombre": "AI Nombre del item",
  "descripcion": "Descripción",
  "tipoOperacion": "Tipo de operación",
  "tipoItem": "Tipo de item",
  "categoria": "Categoría",
  "estadoItem": "Estado Item",
  "estadoRevision": "Estado de revisión",
  "estadoTriangulacion": "Estado de triangulación",
  "estadoDespiece": "Estado de despiece",
  "proveedorCompra": "Proveedor de compra",
  "proveedorLogistico": "Proveedor logístico / intermediario",
  "requierePago": "Requiere pago",
  "pagoRelacionado": "Pago relacionado",
  "requierePacking": "Requiere packing",
  "packingRelacionado": "Packing relacionado",
  "modoLogistico": "Modo logístico",
  "afectaInventario": "Afecta inventario",
  "disponibleVenta": "Disponible para venta",
  "reservado": "Reservado",
  "costoProveedor": "Costo proveedor",
  "fletePacking": "Flete Packing",
  "arancelPacking": "Arancel Packing",
  "otrosCostosPacking": "Otros costos Packing",
  "reglaDistribucionPacking": "Regla distribución Packing",
  "totalCostoProveedorPacking": "Total costo proveedor Packing",
  "cantidadItemsPacking": "Cantidad items Packing",
  "costoFleteAsignado": "Costo flete asignado",
  "costoArancelAsignado": "Costo arancel asignado",
  "otrosCostosAsignados": "Otros costos asignados",
  "costoLogisticoAsignado": "Costo logístico asignado",
  "costoTotalUnidad": "Costo total unidad",
  "precioVentaFinal": "Precio venta final",
  "precioVentaSugerido": "Precio venta sugerido",
  "cantidad": "Cantidad",
  "unidad": "Unidad",
  "skuInterno": "SKU interno",
  "skuProveedor": "SKU proveedor",
  "modelo": "Modelo",
  "marca": "Marca",
  "numeroSerie": "Número de serie",
  "condicion": "Condición",
  "ubicacionActual": "Ubicación actual",
  "trackingDirecto": "Tracking directo",
  "trackingHaciaIntermediario": "Tracking hacia intermediario",
  "trackingDesdeIntermediario": "Tracking desde intermediario",
  "fotos": "Fotos",
  "evidencias": "Evidencias",
  "observacionesInternas": "Observaciones internas",
  "observacionVenta": "Observación para venta",
  "marcaFicha": "Marca ficha",
  "modeloFicha": "Modelo ficha",
  "sistemaOperativo": "Sistema operativo",
  "pantallaTamano": "Pantalla tamaño",
  "pantallaResolucion": "Pantalla resolución",
  "cpuMarca": "CPU marca",
  "cpuModelo": "CPU modelo",
  "cpuFrecuenciaBase": "CPU frecuencia base",
  "cpuFrecuenciaTurbo": "CPU frecuencia turbo",
  "ramCapacidad": "RAM capacidad",
  "ramTipo": "RAM tipo",
  "almacenamientoPrincipal": "Almacenamiento principal",
  "almacenamientoTipo": "Almacenamiento tipo",
  "gpu": "GPU",
  "bateriaSalud": "Batería salud %",
  "bateriaEstado": "Batería estado",
  "conectividadV2": "Conectividad V2",
  "puertosV2": "Puertos V2",
  "caracteristicasExtrasV2": "Características extras V2",
  "observacionFichaTecnica": "Observación ficha técnica",
  "fichaTecnicaGenerada": "Ficha técnica generada",
  "fichaTecnicaRevisada": "Ficha técnica revisada",
  "fichaTecnicaRevisadaPor": "Ficha técnica revisada por",
  "fechaFichaTecnicaRevisada": "Fecha ficha técnica revisada",
  "fechaFichaTecnicaGenerada": "Fecha ficha técnica generada",
  "fichaTecnicaGeneradaPor": "Ficha técnica generada por",
  "metodoAsignacionSku": "Método de asignación SKU",
  "skuProveedorUsadoComoInterno": "SKU proveedor fue usado como interno",
  "skuDuplicadoDetectado": "SKU duplicado detectado",
  "skuOriginalSugerido": "SKU original sugerido",
  "fechaRegistro": "Fecha de registro",
  "registradoPor": "Registrado por",
  "ultimaActualizacion": "Última actualización",
  "actualizadoPor": "Actualizado por",
  "esRegalo": "Es regalo",
  "esParteRecuperada": "Es parte recuperada",
  "esRepuesto": "Es repuesto",
  "esUsoLocal": "Es uso local",
  "itemId": "SKU"
} as const;

export const SHIPPING_V2_ITEM_SELECT_OPTIONS = {
  "tipoOperacion": [
    "Compra a proveedor",
    "Compra ya pagada",
    "Regalo de proveedor",
    "Encargo enviado a proveedor",
    "Reajuste de inventario",
    "Uso local",
    "Repuesto",
    "Parte / componente",
    "Despiece de equipo",
    "Migración histórica",
    "Corrección administrativa"
  ],
  "tipoItem": [
    "Equipo completo",
    "Componente",
    "Parte",
    "Repuesto",
    "Accesorio",
    "Uso local",
    "Otro"
  ],
  "categoria": [
    "Laptop",
    "Desktop",
    "All in One",
    "Monitor",
    "Consola",
    "RAM",
    "SSD",
    "HDD",
    "Pantalla",
    "Teclado",
    "Batería",
    "Cargador",
    "Mainboard",
    "Tarjeta gráfica",
    "Fuente de poder",
    "Cable",
    "Accesorio",
    "Repuesto",
    "Otro"
  ],
  "estadoItem": [
    "Registrado",
    "Pendiente de pago",
    "Pagado",
    "Pendiente de packing",
    "En packing",
    "En tránsito",
    "Recibido",
    "En revisión",
    "Disponible",
    "Reservado",
    "Vendido",
    "Uso local",
    "Repuesto",
    "Usado en reparación",
    "Con novedad",
    "En garantía con proveedor",
    "Destinado a partes",
    "Desarmado parcialmente",
    "Desarmado completamente",
    "Migrado",
    "Cancelado",
    "Archivado"
  ],
  "estadoRevision": [
    "No aplica",
    "Pendiente de recepción",
    "Recibido pendiente de revisión",
    "Recibido correctamente",
    "Faltante",
    "Dañado",
    "Incompleto",
    "Diferente al comprado",
    "En garantía con proveedor",
    "Aceptado con observación"
  ],
  "estadoTriangulacion": [
    "No aplica",
    "Pendiente de envío a intermediario",
    "En camino a intermediario",
    "Recibido por intermediario",
    "Asignado a packing de intermediario",
    "En tránsito desde intermediario",
    "Recibido en destino",
    "Con novedad",
    "Cancelado"
  ],
  "estadoDespiece": [
    "No aplica",
    "Evaluando despiece",
    "Destinado a partes",
    "Despiece en proceso",
    "Despiece parcial",
    "Despiece completo",
    "Cancelado"
  ],
  "modoLogistico": [
    "No aplica",
    "Crear packing individual",
    "Pendiente de packing",
    "Tracking directo",
    "Asignar a packing existente"
  ],
  "unidad": [
    "Unidad",
    "Lote",
    "Pieza",
    "Kit",
    "Otro"
  ],
  "condicion": [
    "Usado",
    "Open Box",
    "Nuevo",
    "Para partes",
    "Dañado",
    "No probado",
    "Reacondicionado",
    "Otro"
  ],
  "sistemaOperativo": [
    "Windows 11 Pro",
    "Windows 11 Home",
    "Windows 10 Pro",
    "Windows 10 Home",
    "ChromeOS",
    "macOS",
    "Linux",
    "Sin sistema",
    "No aplica",
    "Otro"
  ],
  "pantallaTamano": [
    "No aplica",
    "10.1\"",
    "10.8\"",
    "11.6\"",
    "12\"",
    "12.1\"",
    "12.3\"",
    "12.5\"",
    "13\"",
    "13.3\"",
    "13.5\"",
    "14\"",
    "15\"",
    "15.6\"",
    "16\"",
    "17\"",
    "17.3\"",
    "Otro"
  ],
  "pantallaResolucion": [
    "No aplica",
    "1366x768 (HD)",
    "1600x900 (HD+)",
    "1920x1080 (FHD)",
    "1920x1200 (FHD+)",
    "2160x1440 (2K)",
    "2256x1504 (2.2K)",
    "2560x1440 (QHD / 2K)",
    "2560x1600 (2.5K)",
    "2880x1800 (3K)",
    "3000x2000 (3K)",
    "3200x1800 (QHD+)",
    "3840x2160 (4K UHD)",
    "Touch",
    "Otro"
  ],
  "cpuMarca": [
    "Intel",
    "AMD",
    "Apple",
    "Qualcomm",
    "Otro"
  ],
  "ramCapacidad": [
    "2GB",
    "4GB",
    "6GB",
    "8GB",
    "12GB",
    "16GB",
    "24GB",
    "32GB",
    "64GB",
    "128GB",
    "Otro"
  ],
  "ramTipo": [
    "DDR3",
    "DDR3L",
    "DDR4",
    "DDR5",
    "LPDDR3",
    "LPDDR4",
    "LPDDR4X",
    "LPDDR5",
    "LPDDR5X",
    "Otro",
    "No especificado"
  ],
  "almacenamientoTipo": [
    "SSD",
    "M.2 SSD",
    "NVMe SSD",
    "HDD",
    "eMMC",
    "Fusion Drive",
    "Sin almacenamiento",
    "Otro",
    "No especificado"
  ],
  "bateriaEstado": [
    "No aplica",
    "Excelente",
    "Muy buena",
    "Buena / Aceptable",
    "Regular / Requiere Servicio",
    "Mala / Agotada"
  ],
  "metodoAsignacionSku": [
    "Usado desde proveedor",
    "Generado automáticamente",
    "Generado por duplicado",
    "Asignado manualmente",
    "Migrado",
    "No migrado",
    "Listo para migrar"
  ]
} as const;

export const SHIPPING_V2_PROVIDER_FIELDS = {
  "proveedorId": "Proveedor ID",
  "nombre": "Nombre proveedor",
  "estado": "Estado proveedor",
  "tipoProveedor": "Tipo de proveedor",
  "puedeArmarPackings": "Puede armar packings",
  "puedeRecibirEncargosTerceros": "Puede recibir encargos de terceros",
  "permiteTriangulacion": "Permite triangulación",
  "paisZonaLogistica": "País / zona logística",
  "urlRastreo": "URL rastreo",
  "plantillaUrlRastreo": "Plantilla URL rastreo",
  "permiteRastreoWeb": "Permite rastreo web",
  "notasRastreo": "Notas de rastreo"
} as const;

export const SHIPPING_V2_PROVIDER_SELECT_OPTIONS = {
  "estado": [
    "Activo",
    "Inactivo",
    "En revisión"
  ],
  "tipoProveedor": [
    "USA",
    "Local",
    "Marketplace",
    "Interno",
    "Logístico",
    "Otro"
  ],
  "paisZonaLogistica": [
    "USA",
    "Ecuador",
    "Miami / Casillero",
    "Internacional",
    "Local",
    "Otro"
  ]
} as const;

export const SHIPPING_V2_PAYMENT_FIELDS = {
  "pagoId": "Pago ID",
  "estadoPago": "Estado Pago",
  "proveedor": "Proveedor",
  "itemsRelacionados": "Items relacionados",
  "totalAPagar": "Total a pagar",
  "totalPagado": "Total pagado",
  "saldoPendiente": "Saldo pendiente",
  "regalosIncluidos": "Regalos incluidos",
  "fechaCreacion": "Fecha de creación",
  "fechaVencimientoSugerida": "Fecha de vencimiento sugerida",
  "fechaPagoReal": "Fecha real de pago",
  "metodoPago": "Método de pago",
  "cuentaOrigen": "Cuenta origen",
  "transaccionId": "Transacción ID",
  "comprobante": "Comprobante",
  "facturaProveedor": "Factura proveedor",
  "observacion": "Observación",
  "registradoPor": "Registrado por",
  "pagadoPor": "Pagado por",
  "fechaAnulacion": "Fecha de anulación",
  "motivoAnulacion": "Motivo de anulación",
  "estadoIntegracionFinanzas": "Estado de integración con Finanzas",
  "movimientosFinanzas": "Shipping Finanzas Movimientos"
} as const;

export const SHIPPING_V2_PAYMENT_SELECT_OPTIONS = {
  "estadoPago": [
    "Borrador",
    "Pendiente",
    "Parcial",
    "Pagado",
    "En revisión",
    "Anulado"
  ],
  "metodoPago": [
    "Transferencia bancaria",
    "PayPal",
    "Efectivo",
    "Tarjeta",
    "Depósito",
    "Otro",
    "No aplica"
  ],
  "cuentaOrigen": [
    "Tarjeta C. Pichincha",
    "Tarjeta D. Supe Geek ",
    "Tarjeta C. Pacificard",
    "Tarjeta C. Produbanco",
    "Caja",
    "PayPal",
    "Otra",
    "No aplica"
  ],
  "estadoIntegracionFinanzas": [
    "No aplica",
    "Pendiente de generar",
    "Pendiente de sincronizar",
    "Sincronizado",
    "Error",
    "Anulado"
  ]
} as const;

export const SHIPPING_V2_FINANCE_FIELDS = {
  "movimientoShippingId": "Movimiento Shipping ID",
  "origen": "Origen",
  "tipoMovimiento": "Tipo de movimiento",
  "estadoIntegracion": "Estado de integración",
  "pagoShippingRelacionado": "Pago Shipping relacionado",
  "proveedor": "Proveedor",
  "monto": "Monto",
  "fechaMovimiento": "Fecha del movimiento",
  "metodo": "Método",
  "cuentaOrigen": "Cuenta origen",
  "transaccionId": "Transacción ID",
  "comprobante": "Comprobante",
  "movimientoFinanzasIdFuturo": "Movimiento Finanzas ID futuro",
  "errorSincronizacion": "Error de sincronización",
  "fechaSincronizacion": "Fecha de sincronización",
  "observacion": "Observación",
  "registradoPor": "Registrado por",
  "fechaCreacion": "Fecha de creación",
  "fechaAnulacion": "Fecha de anulación",
  "motivoAnulacion": "Motivo de anulación"
} as const;

export const SHIPPING_V2_FINANCE_SELECT_OPTIONS = {
  "origen": [
    "Shipping"
  ],
  "tipoMovimiento": [
    "Egreso",
    "Ingreso",
    "Ajuste",
    "No aplica"
  ],
  "estadoIntegracion": [
    "No aplica",
    "Pendiente de generar",
    "Pendiente de sincronizar",
    "Sincronizado",
    "Error",
    "Anulado"
  ],
  "metodo": [
    "Transferencia bancaria",
    "PayPal",
    "Efectivo",
    "Tarjeta",
    "Depósito",
    "Otro",
    "No aplica"
  ],
  "cuentaOrigen": [
    "Banco Pichincha",
    "Caja",
    "PayPal",
    "Tarjeta",
    "Otra",
    "No aplica"
  ]
} as const;

export const SHIPPING_V2_PACKING_FIELDS = {
  "packingId": "Packing ID",
  "nombre": "Nombre Packing",
  "tipo": "Tipo de packing",
  "estado": "Estado Packing",
  "proveedorResponsable": "Proveedor responsable",
  "proveedorLogisticoEc": "Proveedor logístico EC",
  "itemsIncluidos": "Items incluidos",
  "costoTotalItemsProveedor": "Costo Total Items Proveedor",
  "cantidadItemsPacking": "Cantidad Items Packing",
  "trackingUsa": "Tracking USA",
  "transportistaUsa": "Transportista USA",
  "trackingEc": "Tracking EC",
  "transportistaEc": "Transportista EC",
  "peso": "Peso",
  "flete": "Flete",
  "arancel": "Arancel",
  "otrosCostos": "Otros costos",
  "reglaDistribucionCostos": "Regla de distribución de costos",
  "observacionCostos": "Observación de costos",
  "observaciones": "Observaciones",
  "fechaCreacion": "Fecha de creación",
  "fechaCierre": "Fecha de cierre",
  "fechaEnvio": "Fecha de envío",
  "fechaRecepcion": "Fecha de recepción",
  "cerradoPor": "Cerrado por",
  "creadoPor": "Creado por"
} as const;

export const SHIPPING_V2_PACKING_SELECT_OPTIONS = {
  "tipo": [
    "Caja",
    "Paquete",
    "Sobre",
    "Pallet",
    "Lote físico",
    "Otro"
  ],
  "estado": [
    "En Proceso",
    "Cerrado",
    "En tránsito",
    "Recibido",
    "En revisión",
    "Con novedad",
    "Cancelado",
    "Cerrado final"
  ],
  "reglaDistribucionCostos": [
    "Por costo del item",
    "Por peso",
    "Por cantidad",
    "Manual",
    "No definida"
  ]
} as const;

export const SHIPPING_V2_CPU_CATALOG_FIELDS = {
  "cpuModel": "CPU modelo",
  "cpuBrand": "CPU marca",
  "baseFrequency": "Frecuencia base",
  "turboFrequency": "Frecuencia turbo",
  "originalFrequency": "Frecuencia original",
  "suggestedRamType": "RAM tipo sugerida",
  "integratedGpu": "GPU integrada",
  "sourceName": "Fuente nombre",
  "sourceUrl": "Fuente",
  "verified": "Verificado",
  "usageCount": "Veces usado",
  "lastReviewedAt": "Última revisión",
  "notes": "Observaciones"
} as const;

export const SHIPPING_V2_CPU_CATALOG_SELECT_OPTIONS = {
  "cpuBrand": [
    "Intel",
    "AMD",
    "Apple",
    "Qualcomm",
    "Otro",
    "CPU marca"
  ],
  "suggestedRamType": [
    "DDR3",
    "DDR3L",
    "DDR4",
    "DDR5",
    "LPDDR3",
    "LPDDR4",
    "LPDDR4X",
    "LPDDR5",
    "LPDDR5X",
    "Otro",
    "No especificado",
    "RAM tipo sugerida"
  ]
} as const;

export const SHIPPING_V2_COMPUTER_CATALOG_FIELDS = {
  "computerModel": "Modelo computador",
  "brand": "Marca",
  "suggestedScreenSize": "Pantalla tamaño sugerida",
  "suggestedScreenResolution": "Pantalla resolución sugerida",
  "suggestedOperatingSystem": "Sistema operativo sugerido",
  "suggestedConnectivityV2": "Conectividad sugerida V2",
  "suggestedPortsV2": "Puertos sugeridos V2",
  "suggestedExtraFeaturesV2": "Características extras sugeridas V2",
  "batteryApplies": "Batería aplica",
  "suggestedGpu": "GPU sugerida",
  "sourceName": "Fuente nombre",
  "sourceUrl": "Fuente",
  "verified": "Verificado",
  "usageCount": "Veces usado",
  "lastReviewedAt": "Última revisión",
  "notes": "Observaciones"
} as const;

export const SHIPPING_V2_COMPUTER_CATALOG_SELECT_OPTIONS = {
  "brand": [
    "ACEPC",
    "ASUS",
    "Acer",
    "Apple",
    "Asus ROG",
    "Azulle",
    "Clevo",
    "Dell",
    "HP",
    "Intel",
    "LG",
    "Lenovo",
    "MSI",
    "Microsoft",
    "Samsung",
    "Zotac",
    "Otro",
    "Marca"
  ],
  "suggestedScreenSize": [
    "No aplica",
    "10\"",
    "10.3\"",
    "10.8\"",
    "11.6\"",
    "12.2\"",
    "12.3\"",
    "12.5\"",
    "13\"",
    "13.3\"",
    "14\"",
    "15.4\"",
    "15.6\"",
    "16\"",
    "17.3\"",
    "21.5\"",
    "21.5\" 4K",
    "Otro",
    "Pantalla tamaño sugerida"
  ],
  "suggestedScreenResolution": [
    "No aplica",
    "1366x768 (HD)",
    "1440x900",
    "1600x900 (HD+)",
    "1800x1200",
    "1920x1080 (FHD)",
    "1920x1200 (FHD+)",
    "2400x1600 (2.5K)",
    "2560x1440 (QHD / 2K)",
    "2560x1600 (2.5K)",
    "2880x1800 (3K)",
    "3072x1920 (Retina)",
    "3840x2160 (4K UHD)",
    "4096x2304 (4K Retina)",
    "Otro",
    "Pantalla resolución sugerida"
  ],
  "suggestedOperatingSystem": [
    "Windows 11 Pro",
    "Windows 11 Home",
    "Windows 10 Pro",
    "Windows 10 Home",
    "Windows 10 miniOS",
    "ChromeOS",
    "macOS Sonoma",
    "macOS Sequoia",
    "macOS Ventura",
    "macOS Monterey",
    "Linux",
    "Linux Mint",
    "Sin sistema",
    "No aplica",
    "Otro",
    "Sistema operativo sugerido"
  ],
  "batteryApplies": [
    "Sí",
    "No",
    "No especificado",
    "Batería aplica"
  ]
} as const;

export const SHIPPING_V2_CONNECTIVITY_CATALOG_FIELDS = {
  "name": "Nombre",
  "aliases": "Alias",
  "active": "Activo",
  "order": "Orden",
  "description": "Descripción",
  "createdFromPortal": "Creado desde Portal",
  "createdAt": "Fecha creación",
  "createdBy": "Creado por",
  "notes": "Observaciones"
} as const;

export const SHIPPING_V2_PORTS_CATALOG_FIELDS = {
  "name": "Nombre",
  "aliases": "Alias",
  "active": "Activo",
  "order": "Orden",
  "description": "Descripción",
  "createdFromPortal": "Creado desde Portal",
  "createdAt": "Fecha creación",
  "createdBy": "Creado por",
  "notes": "Observaciones"
} as const;

export const SHIPPING_V2_EXTRA_FEATURES_CATALOG_FIELDS = {
  "name": "Nombre",
  "aliases": "Alias",
  "active": "Activo",
  "order": "Orden",
  "description": "Descripción",
  "createdFromPortal": "Creado desde Portal",
  "createdAt": "Fecha creación",
  "createdBy": "Creado por",
  "notes": "Observaciones"
} as const;

export const SHIPPING_V2_EXPECTED_ITEM_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Nombre del item",
    "AI Nombre del item",
    "SKU",
    "Descripción",
    "Tipo de operación",
    "Tipo de item",
    "Categoría",
    "Estado Item",
    "Estado de revisión",
    "Estado de triangulación",
    "Estado de despiece",
    "Proveedor de compra",
    "Proveedor logístico / intermediario",
    "Requiere pago",
    "Pago relacionado",
    "Requiere packing",
    "Packing relacionado",
    "Afecta inventario",
    "Disponible para venta",
    "Reservado",
    "Costo proveedor",
    "Costo asignado por despiece",
    "Costo total estimado",
    "Precio venta sugerido",
    "Precio venta final",
    "Cantidad",
    "Total costo proveedor Packing",
    "Cantidad items Packing",
    "Costo flete asignado",
    "Costo arancel asignado",
    "Otros costos asignados",
    "Costo logístico asignado",
    "Costo total unidad",
    "Unidad",
    "SKU interno",
    "SKU proveedor",
    "Número de serie",
    "Modelo",
    "Marca",
    "Condición",
    "Ubicación actual",
    "Origen físico actual",
    "Tracking hacia intermediario",
    "Tracking desde intermediario",
    "Tracking directo",
    "Item padre",
    "Items hijos",
    "Motivo de despiece",
    "Fecha de despiece",
    "Responsable de despiece",
    "Es regalo",
    "Es parte recuperada",
    "Es repuesto",
    "Es uso local",
    "Fotos",
    "Evidencias",
    "Observaciones internas",
    "Observación para venta",
    "Fecha de registro",
    "Registrado por",
    "Última actualización",
    "Actualizado por",
    "Legacy Item ID",
    "Legacy Pago ID",
    "Legacy Packing ID",
    "Fuente de migración",
    "Estado de migración",
    "Shipping Pagos (Items relacionados)",
    "Shipping Pagos (Regalos incluidos)",
    "Shipping Packings",
    "Shipping Recepciones",
    "Shipping Novedades",
    "Shipping Migraciones",
    "Shipping Eventos",
    "Método de asignación SKU",
    "SKU proveedor fue usado como interno",
    "SKU duplicado detectado",
    "SKU original sugerido",
    "Modo logístico",
    "Arancel Packing",
    "Flete Packing",
    "Otros costos Packing",
    "Regla distribución Packing",
    "Revisado física/técnicamente",
    "Revisado por",
    "Fecha revisión",
    "Fotos tomadas",
    "Fotos tomadas por",
    "Fecha fotos",
    "Shopify publicado",
    "Shopify publicado por",
    "Fecha Shopify publicado",
    "Marketplace publicado",
    "Marketplace publicado por",
    "Fecha Marketplace publicado",
    "Mercado Libre publicado",
    "Mercado Libre publicado por",
    "Fecha Mercado Libre publicado",
    "Grupos Facebook publicado",
    "Facebook publicado por",
    "Fecha Facebook publicado",
    "Observación recepción",
    "Ficha técnica generada por",
    "Marca ficha",
    "Modelo ficha",
    "Sistema operativo",
    "Pantalla tamaño",
    "Pantalla resolución",
    "CPU marca",
    "CPU modelo",
    "CPU frecuencia base",
    "CPU frecuencia turbo",
    "RAM capacidad",
    "RAM tipo",
    "Almacenamiento principal",
    "Almacenamiento tipo",
    "GPU",
    "Batería salud %",
    "Batería estado",
    "Conectividad",
    "Puertos",
    "Características extras",
    "Observación ficha técnica",
    "Ficha técnica generada",
    "Ficha técnica revisada",
    "Ficha técnica revisada por",
    "Fecha ficha técnica revisada",
    "Fecha ficha técnica generada",
    "Conectividad V2",
    "Puertos V2",
    "Características extras V2",
    "Shipping Destinatarios"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_PROVIDER_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Proveedor ID",
    "Nombre proveedor",
    "Estado proveedor",
    "Tipo de proveedor",
    "País / zona logística",
    "URL rastreo",
    "Plantilla URL rastreo",
    "Permite rastreo web",
    "Notas de rastreo"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_PAYMENT_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Pago ID",
    "Estado Pago",
    "Proveedor",
    "Items relacionados",
    "Total a pagar",
    "Regalos incluidos",
    "Fecha de creación",
    "Fecha de vencimiento sugerida",
    "Fecha real de pago",
    "Método de pago",
    "Cuenta origen",
    "Transacción ID",
    "Comprobante",
    "Observación",
    "Registrado por",
    "Estado de integración con Finanzas",
    "Shipping Finanzas Movimientos"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_FINANCE_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Movimiento Shipping ID",
    "Origen",
    "Tipo de movimiento",
    "Estado de integración",
    "Pago Shipping relacionado",
    "Proveedor",
    "Monto",
    "Fecha del movimiento",
    "Método",
    "Cuenta origen",
    "Transacción ID",
    "Comprobante",
    "Observación",
    "Registrado por",
    "Fecha de creación"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_PACKING_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Packing ID",
    "Nombre Packing",
    "Tipo de packing",
    "Estado Packing",
    "Proveedor responsable",
    "Items incluidos",
    "Costo Total Items Proveedor",
    "Cantidad Items Packing",
    "Tracking USA",
    "Transportista USA",
    "Proveedor logístico EC",
    "Tracking EC",
    "Transportista EC",
    "Peso",
    "Flete",
    "Arancel",
    "Otros costos",
    "Regla de distribución de costos",
    "Observación de costos",
    "Observaciones",
    "Fecha de creación",
    "Fecha de cierre",
    "Fecha de envío",
    "Fecha de recepción",
    "Cerrado por",
    "Creado por"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_CPU_CATALOG_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "CPU modelo",
    "CPU marca",
    "Frecuencia base",
    "Frecuencia turbo",
    "Frecuencia original",
    "RAM tipo sugerida",
    "GPU integrada",
    "Fuente nombre",
    "Fuente",
    "Verificado",
    "Veces usado",
    "Última revisión",
    "Observaciones"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_COMPUTER_CATALOG_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Modelo computador",
    "Marca",
    "Pantalla tamaño sugerida",
    "Pantalla resolución sugerida",
    "Sistema operativo sugerido",
    "Conectividad sugerida V2",
    "Puertos sugeridos V2",
    "Características extras sugeridas V2",
    "Batería aplica",
    "GPU sugerida",
    "Fuente nombre",
    "Fuente",
    "Verificado",
    "Veces usado",
    "Última revisión",
    "Observaciones"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_CONNECTIVITY_CATALOG_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Nombre"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_PORTS_CATALOG_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Nombre"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_EXTRA_FEATURES_CATALOG_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Nombre"
  ],
  "missing": [],
  "similar": {}
} as const;

export function assertShippingV2GeneratedSchema() {
  if (!SHIPPING_V2_EXPECTED_ITEM_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_ITEM_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_PROVIDER_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Proveedores desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_PROVIDER_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_PAYMENT_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Pagos desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_PAYMENT_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_FINANCE_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Finanzas desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_FINANCE_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_PACKING_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Packings desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_PACKING_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_CPU_CATALOG_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Catálogo CPUs desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_CPU_CATALOG_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_COMPUTER_CATALOG_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Catálogo Computadores desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_COMPUTER_CATALOG_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_CONNECTIVITY_CATALOG_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Catálogo Conectividad desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_CONNECTIVITY_CATALOG_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_PORTS_CATALOG_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Catálogo Puertos desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_PORTS_CATALOG_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_EXTRA_FEATURES_CATALOG_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Catálogo Características Extras desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_EXTRA_FEATURES_CATALOG_FIELDS_VALIDATION.missing.join(", ")}`);
  }
}
