/* eslint-disable */
// This file is generated by scripts/inspect-shipping-v2-schema.mjs.
// Do not edit by hand. Run: npm run shipping-v2:schema

export const SHIPPING_V2_SCHEMA_GENERATED_AT = "2026-06-07T23:00:36.018Z";

export const SHIPPING_V2_TABLES = {
  "proveedores": "Shipping Proveedores",
  "items": "Shipping Items",
  "pagos": "Shipping Pagos",
  "finanzasMovimientos": "Shipping Finanzas Movimientos",
  "packings": "Shipping Packings",
  "recepciones": "Shipping Recepciones",
  "novedades": "Shipping Novedades",
  "migraciones": "Shipping Migraciones",
  "eventos": "Shipping Eventos"
} as const;

export const SHIPPING_V2_ITEM_FIELDS = {
  "sku": "SKU",
  "nombre": "Nombre del item",
  "aiNombre": "AI Nombre del item",
  "descripcion": "Descripción",
  "tipoOperacion": "Tipo de operación",
  "tipoItem": "Tipo de item",
  "categoria": "Categoría",
  "estadoItem": "Estado Item",
  "estadoRevision": "Estado de revisión",
  "estadoTriangulacion": "Estado de triangulación",
  "estadoDespiece": "Estado de despiece",
  "proveedorCompra": "Proveedor de compra",
  "proveedorLogistico": "Proveedor logístico / intermediario",
  "requierePago": "Requiere pago",
  "pagoRelacionado": "Pago relacionado",
  "requierePacking": "Requiere packing",
  "packingRelacionado": "Packing relacionado",
  "modoLogistico": "Modo logístico",
  "afectaInventario": "Afecta inventario",
  "disponibleVenta": "Disponible para venta",
  "reservado": "Reservado",
  "costoProveedor": "Costo proveedor",
  "fletePacking": "Flete Packing",
  "arancelPacking": "Arancel Packing",
  "otrosCostosPacking": "Otros costos Packing",
  "reglaDistribucionPacking": "Regla distribución Packing",
  "totalCostoProveedorPacking": "Total costo proveedor Packing",
  "cantidadItemsPacking": "Cantidad items Packing",
  "costoFleteAsignado": "Costo flete asignado",
  "costoArancelAsignado": "Costo arancel asignado",
  "otrosCostosAsignados": "Otros costos asignados",
  "costoLogisticoAsignado": "Costo logístico asignado",
  "costoTotalUnidad": "Costo total unidad",
  "precioVentaFinal": "Precio venta final",
  "precioVentaSugerido": "Precio venta sugerido",
  "cantidad": "Cantidad",
  "unidad": "Unidad",
  "skuInterno": "SKU interno",
  "skuProveedor": "SKU proveedor",
  "modelo": "Modelo",
  "marca": "Marca",
  "numeroSerie": "Número de serie",
  "condicion": "Condición",
  "ubicacionActual": "Ubicación actual",
  "trackingDirecto": "Tracking directo",
  "trackingHaciaIntermediario": "Tracking hacia intermediario",
  "trackingDesdeIntermediario": "Tracking desde intermediario",
  "fotos": "Fotos",
  "evidencias": "Evidencias",
  "observacionesInternas": "Observaciones internas",
  "observacionVenta": "Observación para venta",
  "metodoAsignacionSku": "Método de asignación SKU",
  "skuProveedorUsadoComoInterno": "SKU proveedor fue usado como interno",
  "skuDuplicadoDetectado": "SKU duplicado detectado",
  "skuOriginalSugerido": "SKU original sugerido",
  "fechaRegistro": "Fecha de registro",
  "registradoPor": "Registrado por",
  "ultimaActualizacion": "Última actualización",
  "actualizadoPor": "Actualizado por",
  "esRegalo": "Es regalo",
  "esParteRecuperada": "Es parte recuperada",
  "esRepuesto": "Es repuesto",
  "esUsoLocal": "Es uso local",
  "itemId": "SKU"
} as const;

export const SHIPPING_V2_ITEM_SELECT_OPTIONS = {
  "tipoOperacion": [
    "Compra a proveedor",
    "Compra ya pagada",
    "Regalo de proveedor",
    "Encargo enviado a proveedor",
    "Reajuste de inventario",
    "Uso local",
    "Repuesto",
    "Parte / componente",
    "Despiece de equipo",
    "Migración histórica",
    "Corrección administrativa"
  ],
  "tipoItem": [
    "Equipo completo",
    "Componente",
    "Parte",
    "Repuesto",
    "Accesorio",
    "Uso local",
    "Otro"
  ],
  "categoria": [
    "Laptop",
    "Desktop",
    "All in One",
    "Monitor",
    "Consola",
    "RAM",
    "SSD",
    "HDD",
    "Pantalla",
    "Teclado",
    "Batería",
    "Cargador",
    "Mainboard",
    "Tarjeta gráfica",
    "Fuente de poder",
    "Cable",
    "Accesorio",
    "Repuesto",
    "Otro"
  ],
  "estadoItem": [
    "Registrado",
    "Pendiente de pago",
    "Pagado",
    "Pendiente de packing",
    "En packing",
    "En tránsito",
    "Recibido",
    "En revisión",
    "Disponible",
    "Reservado",
    "Vendido",
    "Uso local",
    "Repuesto",
    "Usado en reparación",
    "Con novedad",
    "En garantía con proveedor",
    "Destinado a partes",
    "Desarmado parcialmente",
    "Desarmado completamente",
    "Migrado",
    "Cancelado",
    "Archivado"
  ],
  "estadoRevision": [
    "No aplica",
    "Pendiente de recepción",
    "Recibido pendiente de revisión",
    "Recibido correctamente",
    "Faltante",
    "Dañado",
    "Incompleto",
    "Diferente al comprado",
    "En garantía con proveedor",
    "Aceptado con observación"
  ],
  "estadoTriangulacion": [
    "No aplica",
    "Pendiente de envío a intermediario",
    "En camino a intermediario",
    "Recibido por intermediario",
    "Asignado a packing de intermediario",
    "En tránsito desde intermediario",
    "Recibido en destino",
    "Con novedad",
    "Cancelado"
  ],
  "estadoDespiece": [
    "No aplica",
    "Evaluando despiece",
    "Destinado a partes",
    "Despiece en proceso",
    "Despiece parcial",
    "Despiece completo",
    "Cancelado"
  ],
  "modoLogistico": [
    "No aplica",
    "Crear packing individual",
    "Pendiente de packing",
    "Tracking directo",
    "Asignar a packing existente"
  ],
  "unidad": [
    "Unidad",
    "Lote",
    "Pieza",
    "Kit",
    "Otro"
  ],
  "condicion": [
    "Usado",
    "Open Box",
    "Nuevo",
    "Para partes",
    "Dañado",
    "No probado",
    "Reacondicionado",
    "Otro"
  ],
  "metodoAsignacionSku": [
    "Usado desde proveedor",
    "Generado automáticamente",
    "Generado por duplicado",
    "Asignado manualmente",
    "Migrado",
    "No migrado",
    "Listo para migrar"
  ]
} as const;

export const SHIPPING_V2_PROVIDER_FIELDS = {
  "proveedorId": "Proveedor ID",
  "nombre": "Nombre proveedor",
  "estado": "Estado proveedor",
  "tipoProveedor": "Tipo de proveedor",
  "puedeArmarPackings": "Puede armar packings",
  "puedeRecibirEncargosTerceros": "Puede recibir encargos de terceros",
  "permiteTriangulacion": "Permite triangulación",
  "paisZonaLogistica": "País / zona logística",
  "urlRastreo": "URL rastreo",
  "plantillaUrlRastreo": "Plantilla URL rastreo",
  "permiteRastreoWeb": "Permite rastreo web",
  "notasRastreo": "Notas de rastreo"
} as const;

export const SHIPPING_V2_PROVIDER_SELECT_OPTIONS = {
  "estado": [
    "Activo",
    "Inactivo",
    "En revisión"
  ],
  "tipoProveedor": [
    "USA",
    "Local",
    "Marketplace",
    "Interno",
    "Logístico",
    "Otro"
  ],
  "paisZonaLogistica": [
    "USA",
    "Ecuador",
    "Miami / Casillero",
    "Internacional",
    "Local",
    "Otro"
  ]
} as const;

export const SHIPPING_V2_PAYMENT_FIELDS = {
  "pagoId": "Pago ID",
  "estadoPago": "Estado Pago",
  "proveedor": "Proveedor",
  "itemsRelacionados": "Items relacionados",
  "totalAPagar": "Total a pagar",
  "totalPagado": "Total pagado",
  "saldoPendiente": "Saldo pendiente",
  "regalosIncluidos": "Regalos incluidos",
  "fechaCreacion": "Fecha de creación",
  "fechaVencimientoSugerida": "Fecha de vencimiento sugerida",
  "fechaPagoReal": "Fecha real de pago",
  "metodoPago": "Método de pago",
  "cuentaOrigen": "Cuenta origen",
  "transaccionId": "Transacción ID",
  "comprobante": "Comprobante",
  "facturaProveedor": "Factura proveedor",
  "observacion": "Observación",
  "registradoPor": "Registrado por",
  "pagadoPor": "Pagado por",
  "fechaAnulacion": "Fecha de anulación",
  "motivoAnulacion": "Motivo de anulación",
  "estadoIntegracionFinanzas": "Estado de integración con Finanzas",
  "movimientosFinanzas": "Shipping Finanzas Movimientos"
} as const;

export const SHIPPING_V2_PAYMENT_SELECT_OPTIONS = {
  "estadoPago": [
    "Borrador",
    "Pendiente",
    "Parcial",
    "Pagado",
    "En revisión",
    "Anulado"
  ],
  "metodoPago": [
    "Transferencia bancaria",
    "PayPal",
    "Efectivo",
    "Tarjeta",
    "Depósito",
    "Otro",
    "No aplica"
  ],
  "cuentaOrigen": [
    "Banco Pichincha",
    "Caja",
    "PayPal",
    "Tarjeta",
    "Otra",
    "No aplica"
  ],
  "estadoIntegracionFinanzas": [
    "No aplica",
    "Pendiente de generar",
    "Pendiente de sincronizar",
    "Sincronizado",
    "Error",
    "Anulado"
  ]
} as const;

export const SHIPPING_V2_FINANCE_FIELDS = {
  "movimientoShippingId": "Movimiento Shipping ID",
  "origen": "Origen",
  "tipoMovimiento": "Tipo de movimiento",
  "estadoIntegracion": "Estado de integración",
  "pagoShippingRelacionado": "Pago Shipping relacionado",
  "proveedor": "Proveedor",
  "monto": "Monto",
  "fechaMovimiento": "Fecha del movimiento",
  "metodo": "Método",
  "cuentaOrigen": "Cuenta origen",
  "transaccionId": "Transacción ID",
  "comprobante": "Comprobante",
  "movimientoFinanzasIdFuturo": "Movimiento Finanzas ID futuro",
  "errorSincronizacion": "Error de sincronización",
  "fechaSincronizacion": "Fecha de sincronización",
  "observacion": "Observación",
  "registradoPor": "Registrado por",
  "fechaCreacion": "Fecha de creación",
  "fechaAnulacion": "Fecha de anulación",
  "motivoAnulacion": "Motivo de anulación"
} as const;

export const SHIPPING_V2_FINANCE_SELECT_OPTIONS = {
  "origen": [
    "Shipping"
  ],
  "tipoMovimiento": [
    "Egreso",
    "Ingreso",
    "Ajuste",
    "No aplica"
  ],
  "estadoIntegracion": [
    "No aplica",
    "Pendiente de generar",
    "Pendiente de sincronizar",
    "Sincronizado",
    "Error",
    "Anulado"
  ],
  "metodo": [
    "Transferencia bancaria",
    "PayPal",
    "Efectivo",
    "Tarjeta",
    "Depósito",
    "Otro",
    "No aplica"
  ],
  "cuentaOrigen": [
    "Banco Pichincha",
    "Caja",
    "PayPal",
    "Tarjeta",
    "Otra",
    "No aplica"
  ]
} as const;

export const SHIPPING_V2_PACKING_FIELDS = {
  "packingId": "Packing ID",
  "nombre": "Nombre Packing",
  "tipo": "Tipo de packing",
  "estado": "Estado Packing",
  "proveedorResponsable": "Proveedor responsable",
  "proveedorLogisticoEc": "Proveedor logístico EC",
  "itemsIncluidos": "Items incluidos",
  "costoTotalItemsProveedor": "Costo Total Items Proveedor",
  "cantidadItemsPacking": "Cantidad Items Packing",
  "trackingUsa": "Tracking USA",
  "transportistaUsa": "Transportista USA",
  "trackingEc": "Tracking EC",
  "transportistaEc": "Transportista EC",
  "peso": "Peso",
  "flete": "Flete",
  "arancel": "Arancel",
  "otrosCostos": "Otros costos",
  "reglaDistribucionCostos": "Regla de distribución de costos",
  "observacionCostos": "Observación de costos",
  "observaciones": "Observaciones",
  "fechaCreacion": "Fecha de creación",
  "fechaCierre": "Fecha de cierre",
  "fechaEnvio": "Fecha de envío",
  "fechaRecepcion": "Fecha de recepción",
  "cerradoPor": "Cerrado por",
  "creadoPor": "Creado por"
} as const;

export const SHIPPING_V2_PACKING_SELECT_OPTIONS = {
  "tipo": [
    "Caja",
    "Paquete",
    "Sobre",
    "Pallet",
    "Lote físico",
    "Otro"
  ],
  "estado": [
    "En Proceso",
    "Cerrado",
    "En tránsito",
    "Recibido",
    "En revisión",
    "Con novedad",
    "Cancelado",
    "Cerrado final"
  ],
  "reglaDistribucionCostos": [
    "Por costo del item",
    "Por peso",
    "Por cantidad",
    "Manual",
    "No definida"
  ]
} as const;

export const SHIPPING_V2_EXPECTED_ITEM_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Nombre del item",
    "AI Nombre del item",
    "SKU",
    "Descripción",
    "Tipo de operación",
    "Tipo de item",
    "Categoría",
    "Estado Item",
    "Estado de revisión",
    "Estado de triangulación",
    "Estado de despiece",
    "Proveedor de compra",
    "Proveedor logístico / intermediario",
    "Requiere pago",
    "Pago relacionado",
    "Requiere packing",
    "Packing relacionado",
    "Afecta inventario",
    "Disponible para venta",
    "Reservado",
    "Costo proveedor",
    "Costo asignado por despiece",
    "Costo total estimado",
    "Precio venta sugerido",
    "Precio venta final",
    "Cantidad",
    "Total costo proveedor Packing",
    "Cantidad items Packing",
    "Costo flete asignado",
    "Costo arancel asignado",
    "Otros costos asignados",
    "Costo logístico asignado",
    "Costo total unidad",
    "Unidad",
    "SKU interno",
    "SKU proveedor",
    "Número de serie",
    "Modelo",
    "Marca",
    "Condición",
    "Ubicación actual",
    "Origen físico actual",
    "Tracking hacia intermediario",
    "Tracking desde intermediario",
    "Tracking directo",
    "Item padre",
    "Items hijos",
    "Motivo de despiece",
    "Fecha de despiece",
    "Responsable de despiece",
    "Es regalo",
    "Es parte recuperada",
    "Es repuesto",
    "Es uso local",
    "Fotos",
    "Evidencias",
    "Observaciones internas",
    "Observación para venta",
    "Fecha de registro",
    "Registrado por",
    "Última actualización",
    "Actualizado por",
    "Legacy Item ID",
    "Legacy Pago ID",
    "Legacy Packing ID",
    "Fuente de migración",
    "Estado de migración",
    "Shipping Pagos (Items relacionados)",
    "Shipping Pagos (Regalos incluidos)",
    "Shipping Packings",
    "Shipping Recepciones",
    "Shipping Novedades",
    "Shipping Migraciones",
    "Shipping Eventos",
    "Método de asignación SKU",
    "SKU proveedor fue usado como interno",
    "SKU duplicado detectado",
    "SKU original sugerido",
    "Modo logístico",
    "Arancel Packing",
    "Flete Packing",
    "Otros costos Packing",
    "Regla distribución Packing",
    "Revisado física/técnicamente",
    "Revisado por",
    "Fecha revisión",
    "Fotos tomadas",
    "Fotos tomadas por",
    "Fecha fotos",
    "Shopify publicado",
    "Shopify publicado por",
    "Fecha Shopify publicado",
    "Marketplace publicado",
    "Marketplace publicado por",
    "Fecha Marketplace publicado",
    "Mercado Libre publicado",
    "Mercado Libre publicado por",
    "Fecha Mercado Libre publicado",
    "Grupos Facebook publicado",
    "Facebook publicado por",
    "Fecha Facebook publicado",
    "Observación recepción"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_PROVIDER_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Proveedor ID",
    "Nombre proveedor",
    "Estado proveedor",
    "Tipo de proveedor",
    "Requiere pago antes de envío",
    "Plazo sugerido de pago en días",
    "Puede armar packings",
    "Puede recibir encargos de terceros",
    "Permite triangulación",
    "Permite acceso portal proveedor",
    "Puede responder novedades o garantías",
    "Método de pago preferido",
    "Cuenta o destino de pago preferido",
    "Regla de distribución de costos preferida",
    "Email de contacto",
    "Teléfono / WhatsApp",
    "Notificar recepción por email",
    "Notificar novedades por email",
    "Permisos especiales",
    "Observaciones",
    "Registrado por",
    "Fecha de creación",
    "Última actualización",
    "Legacy Proveedor ID",
    "Fuente de migración",
    "Shipping Items (Proveedor de compra)",
    "Shipping Items (Proveedor logístico / intermediario)",
    "Shipping Pagos",
    "Shipping Finanzas Movimientos",
    "Shipping Packings (Proveedor responsable)",
    "Shipping Packings (Proveedor logístico / intermediario)",
    "Shipping Recepciones",
    "Shipping Novedades",
    "Shipping Migraciones",
    "Shipping Eventos",
    "Shipping Packings",
    "Shipping Packings 2",
    "País / zona logística",
    "URL rastreo",
    "Plantilla URL rastreo",
    "Permite rastreo web",
    "Notas de rastreo"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_PAYMENT_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Pago ID",
    "Estado Pago",
    "Proveedor",
    "Items relacionados",
    "Total a pagar",
    "Total pagado",
    "Saldo pendiente",
    "Regalos incluidos",
    "Fecha de creación",
    "Fecha de vencimiento sugerida",
    "Fecha real de pago",
    "Método de pago",
    "Cuenta origen",
    "Transacción ID",
    "Comprobante",
    "Factura proveedor",
    "Observación",
    "Registrado por",
    "Pagado por",
    "Fecha de anulación",
    "Motivo de anulación",
    "Estado de integración con Finanzas",
    "Legacy Pago ID",
    "Fuente de migración",
    "Estado de migración",
    "Shipping Finanzas Movimientos",
    "Shipping Migraciones",
    "Shipping Eventos"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_FINANCE_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Movimiento Shipping ID",
    "Origen",
    "Tipo de movimiento",
    "Estado de integración",
    "Pago Shipping relacionado",
    "Proveedor",
    "Monto",
    "Fecha del movimiento",
    "Método",
    "Cuenta origen",
    "Transacción ID",
    "Comprobante",
    "Movimiento Finanzas ID futuro",
    "Error de sincronización",
    "Fecha de sincronización",
    "Observación",
    "Registrado por",
    "Fecha de creación",
    "Fecha de anulación",
    "Motivo de anulación",
    "Shipping Eventos"
  ],
  "missing": [],
  "similar": {}
} as const;

export const SHIPPING_V2_EXPECTED_PACKING_FIELDS_VALIDATION = {
  "ok": true,
  "found": [
    "Packing ID",
    "Nombre Packing",
    "Tipo de packing",
    "Estado Packing",
    "Proveedor responsable",
    "Proveedor logístico EC",
    "Items incluidos",
    "Costo Total Items Proveedor",
    "Cantidad Items Packing",
    "Tracking USA",
    "Transportista USA",
    "Transportista EC",
    "Peso",
    "Flete",
    "Arancel",
    "Otros costos",
    "Regla de distribución de costos",
    "Observación de costos",
    "Fecha de creación",
    "Fecha de cierre",
    "Fecha de envío",
    "Fecha de recepción",
    "Recibido por",
    "Cerrado por",
    "Enviado por",
    "Creado por",
    "Evidencias",
    "Comprobante flete / arancel",
    "Observaciones",
    "Motivo de cancelación",
    "Fecha de cancelación",
    "Legacy Packing ID",
    "Fuente de migración",
    "Estado de migración",
    "Shipping Recepciones",
    "Shipping Novedades",
    "Shipping Migraciones",
    "Shipping Eventos",
    "Tracking EC"
  ],
  "missing": [],
  "similar": {}
} as const;

export function assertShippingV2GeneratedSchema() {
  if (!SHIPPING_V2_EXPECTED_ITEM_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_ITEM_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_PROVIDER_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Proveedores desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_PROVIDER_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_PAYMENT_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Pagos desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_PAYMENT_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_FINANCE_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Finanzas desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_FINANCE_FIELDS_VALIDATION.missing.join(", ")}`);
  }
  if (!SHIPPING_V2_EXPECTED_PACKING_FIELDS_VALIDATION.ok) {
    throw new Error(`Schema Shipping V2 Packings desactualizado o incompleto. Ejecuta npm run shipping-v2:schema. Campos faltantes: ${SHIPPING_V2_EXPECTED_PACKING_FIELDS_VALIDATION.missing.join(", ")}`);
  }
}
